"""
Django settings for budget_tracker project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from pathlib import Path
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
key = None
with open('secret.key') as f:
    key = f.read().strip()

SECRET_KEY = key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['fintrack.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'registration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'budget_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'DIRS': [BASE_DIR / 'templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'budget_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Login redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

#  Session Cookie Settings
# Session expires when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Session lasts 2 weeks (in seconds)
SESSION_COOKIE_AGE = 1209600

# Cookie only sent over HTTPS
# (set True in production)
SESSION_COOKIE_SECURE = False

# Prevents JavaScript accessing cookie
SESSION_COOKIE_HTTPONLY = True

# Cookie name
SESSION_COOKIE_NAME = 'sessionid'

#  CSRF Cookie Settings
# CSRF cookie only sent over HTTPS
# (set True in production)
CSRF_COOKIE_SECURE = False

# Prevents JavaScript accessing CSRF cookie
CSRF_COOKIE_HTTPONLY = False

# CSRF cookie age (1 year in seconds)
CSRF_COOKIE_AGE = 31449600

#  Security Settings
# Prevents clickjacking
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Prevents browser sniffing mime types
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enables XSS filtering in browser
SECURE_BROWSER_XSS_FILTER = True

#Registration Settins
# If True, users can register
# Set False to disable registration
REGISTRATION_OPEN = True

# If True, user is automatically
# logged in after registering
REGISTRATION_AUTO_LOGIN = True

# The URL Django redirects users
# to after logging in
LOGIN_REDIRECT_URL = '/dashboard/'

# The page users are directed to
# if they are not logged in
# Used by @login_required decorator
LOGIN_URL = '/login/'

# The page users are directed to
# after logging out
LOGOUT_REDIRECT_URL = '/login/'